"use client";
import {useState} from "react";
type Mode="personal"|"business"|null; type Relationship="Lover"|"Crush"|"Family"|"Friend";
export default function Home(){
 const [mode,setMode]=useState<Mode>(null),[scope,setScope]=useState<"all"|"selected">("all"),[relationship,setRelationship]=useState<Relationship>("Lover");
 return <div className="shell"><header className="top"><div className="brand"><div className="logo">W</div>WhatsApp AI</div><div className="status">Ready to connect</div></header><main className="main"><section className="hero"><h1>Your replies.<br/>Handled naturally.</h1><p>Choose where AI can help, keep control of every chat, and let the assistant wait for you before replying automatically.</p></section>
 {!mode?<div className="grid"><button className="card mode" onClick={()=>setMode("personal")}><div className="emoji">👤</div><h2>Personal</h2><p>Lover, Crush, Family or Friend. AI adapts to the relationship and emotion.</p></button><button className="card mode" onClick={()=>setMode("business")}><div className="emoji">💼</div><h2>Business</h2><p>Answer customers using your business information, prices, hours and FAQs.</p></button></div>
 :<section className="card panel"><div className="row"><div><div className="label">Mode</div><div className="value">{mode==="personal"?"👤 Personal":"💼 Business"}</div></div><button className="secondary" onClick={()=>setMode(null)}>Change</button></div><div className="row"><div><div className="label">WhatsApp</div><div className="value">Not connected yet</div></div><span className="pill"><span className="dot"/> Offline</span></div><div className="choice"><div className="label">Who should AI handle?</div><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>All chats</button><button className={scope==="selected"?"active":""} onClick={()=>setScope("selected")}>Selected contacts only</button></div>
 {mode==="personal"&&<div className="choice"><div className="label">Relationship for selected contacts</div>{(["Lover","Crush","Family","Friend"] as Relationship[]).map(x=><button key={x} className={relationship===x?"active":""} onClick={()=>setRelationship(x)}>{x==="Lover"?"❤️":x==="Crush"?"😍":x==="Family"?"👨‍👩‍👧":"🤝"} {x}</button>)}</div>}
 {mode==="business"&&<div className="card" style={{marginTop:14}}><div className="value">Business setup</div><p style={{marginTop:8}}>Add business name, products/services, prices, opening hours, location, FAQs and rules. AI hands off when unsure.</p></div>}
 <div className="actions"><button className="primary">Connect WhatsApp</button><button className="secondary">AI Takeover: OFF</button></div><div className="small">Takeover waits 10 seconds for your manual reply. If you reply first, the pending AI response is cancelled.</div></section>}</main></div>
}