"use client";
import {useEffect,useState} from "react"; import {supabase} from "../lib/supabase";
type Mode="personal"|"business"; type Relationship="lover"|"crush"|"family"|"friend";
const labels:Record<Relationship,string>={lover:"❤️ Lover",crush:"😍 Crush",family:"👨‍👩‍👧 Family",friend:"🤝 Friend"};
export default function Home(){
const [mode,setMode]=useState<Mode>("personal"),[scope,setScope]=useState<"all"|"selected">("all"),[relationship,setRelationship]=useState<Relationship>("lover"),[phone,setPhone]=useState(""),[otp,setOtp]=useState(""),[otpSent,setOtpSent]=useState(false),[userId,setUserId]=useState<string|null>(null),[takeover,setTakeover]=useState(false),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
const [business,setBusiness]=useState({name:"",description:"",location:"",phone:""});
useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();setUserId(data.session?.user.id??null);if(data.session?.user)await loadSettings(data.session.user.id);setLoading(false)})();const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUserId(s?.user.id??null));return()=>data.subscription.unsubscribe()},[]);
async function loadSettings(uid:string){const {data}=await supabase.from("ai_settings").select("mode,auto_reply,personality").eq("user_id",uid).maybeSingle();if(data){setMode(data.mode==="business"?"business":"personal");setTakeover(!!data.auto_reply);if(["lover","crush","family","friend"].includes(data.personality))setRelationship(data.personality as Relationship)}const {data:b}=await supabase.from("business_profiles").select("business_name,description,location,phone").eq("user_id",uid).maybeSingle();if(b)setBusiness({name:b.business_name??"",description:b.description??"",location:b.location??"",phone:b.phone??""})}
async function sendOtp(){setMessage("");if(!phone.trim())return setMessage("Enter your WhatsApp phone number.");const {error}=await supabase.auth.signInWithOtp({phone:phone.trim()});if(error)setMessage(error.message);else{setOtpSent(true);setMessage("Verification code sent.")}}
async function verifyOtp(){const {error}=await supabase.auth.verifyOtp({phone:phone.trim(),token:otp.trim(),type:"sms"});if(error)setMessage(error.message);else setMessage("Account connected.")} 
async function save(){if(!userId)return setMessage("Verify your phone first.");setSaved(false);const {error}=await supabase.from("ai_settings").upsert({user_id:userId,mode,auto_reply:takeover,personality:relationship,system_prompt:mode==="personal"?"Relationship tone: "+relationship+". Adapt naturally to emotion, intent and conversation history.":"",handoff_enabled:true},{onConflict:"user_id"});if(error)return setMessage(error.message);if(mode==="business"){const {error:e}=await supabase.from("business_profiles").upsert({user_id:userId,business_name:business.name||null,description:business.description||null,location:business.location||null,phone:business.phone||null},{onConflict:"user_id"});if(e)return setMessage(e.message)}setSaved(true);setMessage("Settings saved securely.");setTimeout(()=>setSaved(false),2500)}
if(loading)return <div className="loading">Loading your secure workspace…</div>;
return <div className="shell"><header className="top"><div className="brand"><div className="logo">W</div>WhatsApp AI</div><div className={"status "+(userId?"online":"")}>{userId?"Account connected":"Not signed in"}</div></header><main className="main"><section className="hero"><h1>Your replies.<br/>Handled naturally.</h1><p>Connect your account, choose how AI should behave, and keep final control over your WhatsApp conversations.</p></section>
{!userId&&<section className="card auth"><h2>Connect your WhatsApp number</h2><p>We use your number as the account identity. No password is required.</p><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+256 7xx xxx xxx" inputMode="tel"/>{otpSent&&<input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Verification code" inputMode="numeric"/>}<button className="primary" onClick={otpSent?verifyOtp:sendOtp}>{otpSent?"Verify code":"Send verification code"}</button>{message&&<div className="notice">{message}</div>}</section>}
<section className="grid"><button className={"card mode "+(mode==="personal"?"selected":"")} onClick={()=>setMode("personal")}><div className="emoji">👤</div><h2>Personal</h2><p>Lover, Crush, Family or Friend. AI adapts to relationship, emotion and conversation.</p></button><button className={"card mode "+(mode==="business"?"selected":"")} onClick={()=>setMode("business")}><div className="emoji">💼</div><h2>Business</h2><p>Answer customers using your business information and hand off when unsure.</p></button></section>
<section className="card panel"><div className="row"><div><div className="label">AI takeover</div><div className="value">{takeover?"ON — AI can reply automatically":"OFF — you have control"}</div></div><button className={takeover?"danger":"secondary"} onClick={()=>setTakeover(!takeover)}>{takeover?"Turn off":"Turn on"}</button></div><div className="choice"><div className="label">Who should AI handle?</div><button className={scope==="all"?"active":""} onClick={()=>setScope("all")}>All chats</button><button className={scope==="selected"?"active":""} onClick={()=>setScope("selected")}>Selected contacts only</button></div>
{mode==="personal"&&<div className="choice"><div className="label">Default relationship tone</div>{(Object.keys(labels) as Relationship[]).map(x=><button key={x} className={relationship===x?"active":""} onClick={()=>setRelationship(x)}>{labels[x]}</button>)}</div>}
{mode==="business"&&<div className="business"><div className="label">Business knowledge</div><input value={business.name} onChange={e=>setBusiness({...business,name:e.target.value})} placeholder="Business name"/><textarea value={business.description} onChange={e=>setBusiness({...business,description:e.target.value})} placeholder="Products/services, prices, FAQs and rules"/><input value={business.location} onChange={e=>setBusiness({...business,location:e.target.value})} placeholder="Location"/><input value={business.phone} onChange={e=>setBusiness({...business,phone:e.target.value})} placeholder="Business phone"/></div>}
<div className="actions"><button className="primary" onClick={save}>{saved?"Saved ✓":"Save settings"}</button><div className="small">Settings are stored in Supabase with per-user RLS. WhatsApp session connection remains gated until the WAHA server is configured.</div></div>{message&&userId&&<div className="notice">{message}</div>}<div className="small">AI waits 10 seconds for your manual reply. If you reply first, the pending AI response is cancelled.</div></section></main></div>}